test_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: dbt
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: public
      threads: 1
